
(function(){
const SUGO_MISSION_BANK={
 talk:[
 '今の気分を一言で語る','最近ちょっと嬉しかったことを話す','コメントを3件拾う','今日の小さな失敗を話す','昔のあだ名の話をする','地元の好きなところを話す','最近買ってよかった物を話す','好きな食べ物を熱く語る','子どもの頃の思い出を1つ話す','リスナーに二択質問を出す','今だから笑える話をする','最近のマイブームを話す','一番落ち着く場所を話す','今年やりたいことを話す','今日の配信の裏話を話す','最近笑ったコメントを振り返る','忘れられない給食の話をする','好きなコンビニを語る','朝型か夜型か話す','昔ハマった遊びを話す','最近の小さな悩みを話す','人生で一番どうでもいいこだわりを話す','財布の中身を見ずに想像で説明する','好きな季節を理由付きで話す','風呂でどこから洗うか話す','目玉焼きに何をかけるか話す','カレーを混ぜる派か話す','寝る前のルーティンを話す','最近見た変な夢を話す','好きな匂いを話す','苦手な音を話す','スマホのホーム画面事情を話す','初めて買ったCD/曲の話をする','一番使う絵文字を話す','今欲しい謎アイテムを話す','今日の自分に点数を付ける','最近の口癖を話す','小学生の頃の休み時間を話す','一人旅するならどこか話す','最近の失敗をポジティブ変換する','謎に覚えてるCMを話す','好きな駄菓子を語る','得意じゃないけど好きなことを話す','自分の配信を一言で説明する','今の部屋にある一番古い物を話す','好きな麺類を語る','雨の日の過ごし方を話す','暑さ寒さどっちが苦手か話す','最近のプチ贅沢を話す','今日のテンションを天気で例える'
 ],
 listener:[
 'リスナーに今日の晩ご飯を聞く','リスナーに出身地を聞く','リスナーに好きなコンビニ商品を聞く','リスナーに眠気レベルを聞く','リスナーに最近ハマってるものを聞く','リスナーに一文字コメントをもらう','リスナーに二択を投げる','リスナーから次の話題を1つ募集する','初見さん向けに一言挨拶する','コメント欄で多数決を取る','リスナーに今日の点数を聞く','リスナーに好きな季節を聞く','リスナーの地域あるあるを聞く','リスナーに今いる場所の温度感を聞く','リスナーに小さな自慢を募集する','リスナーに好きなおにぎりの具を聞く','リスナーに朝ごはん派か聞く','リスナーに犬派猫派を聞く','リスナーに最近買ってよかった物を聞く','リスナーに寝る時の姿勢を聞く','リスナーに風呂の温度を聞く','リスナーに好きな曜日を聞く','リスナーにスマホケース事情を聞く','リスナーにカラオケ十八番を聞く','リスナーに学生時代の部活を聞く','リスナーに好きなラーメンを聞く','リスナーに旅行したい場所を聞く','リスナーに最近の口癖を聞く','リスナーに今年やりたいことを聞く','リスナーに人生で一番どうでもいい悩みを聞く','リスナーに好きな匂いを聞く','リスナーに苦手な家事を聞く','リスナーに今日の服装を聞く','リスナーに今飲んでる物を聞く','リスナーに好きなアイスを聞く','リスナーに得意料理を聞く','リスナーに一番使うアプリを聞く','リスナーに最近笑ったことを聞く','リスナーに雨の日あるあるを聞く','リスナーに地元の名物を聞く'
 ],
 chaos:[
 '急にラジオDJ風に読む','全力で褒めるだけの30秒','謎の決め台詞を作る','架空のCMを始める','食べ物を必殺技名っぽく言う','自分をRPGキャラとして紹介する','目の前にある物を師匠扱いする','何でもない話を感動話っぽくする','急に裁判を始める','コメント欄を王国に例える','今日の自分に称号を付ける','存在しない商品を紹介する','一番弱そうな魔法を唱える','急に探偵っぽく推理する','宇宙人に配信を説明する','冷蔵庫と会話した体で話す','ペットボトルを敵キャラとして紹介する','自分の椅子に感謝の手紙を読む','5秒だけラスボスになる','今日のコメント欄に国名を付ける','謎の占い師として助言する','見えない店員に注文する','自分の名前に二つ名を付ける','突然ニュースキャスターになる','カレーに謝罪会見させる','スマホを擬人化して褒める','一番しょうもない名言を作る','部屋にある物で冒険パーティを組む','存在しない駅名を作る','配信を昔話っぽく語る','急に校長先生の挨拶をする','おにぎりの気持ちになる','掃除機にインタビューする','自分の弱点を必殺技っぽく言う','3秒だけアイドルになる','リスナーを全員勇者扱いする','今日の空気に名前を付ける','架空の映画予告をする','何でもない単語を怖く読む','急に通販番組を始める'
 ],
 penalty:[
 '早口言脱線候補を1回言う','変な敬語で30秒話す','一発ギャグ未満を言う','黒歴史を薄く話す','今日一番噛みそうな言脱線候補を言う','腕立てかスクワットを少しする','一番恥ずかしい褒め方をする','モノマネを一瞬だけする','全力で謝る演技をする','自分の弱点を1つ言う','変顔を想像させる説明をする','かっこいいセリフを言う','可愛いセリフを言う','厨二病っぽく宣言する','最後の語尾を全部「だべ」にして30秒話す','10秒間だけ超丁寧語で話す','好きな物を全力プレゼンする','苦手な食べ物を褒める','今日の自分を反省会する','リスナーを3人分まとめて褒める','噛まずに長い単語を読む','一番どうでもいい自慢をする','自分の配信のCMを作る','即興で短いポエムを読む','照れずに感謝を言う','小声で名言っぽく言う','架空の罰ゲームを発表する','今の気持ちを動物で表す','30秒だけ語尾を変える','今日の服装を実況する','全力で「すみませんでした」を言う','一番かわいい声を一瞬出す','渋い声で自己紹介する','昨日の自分に説教する','今日の目標を大げさに宣言する','早口で今日の予定を言う','配信タイトルを即興で作る','コメント欄に感謝状を読む','今のミッションをドラマ化する','一番くだらない悩みを真剣に語る'
 ]
};
function sugoPick(a){return a[Math.floor(Math.random()*a.length)]}
function sugoState(){window.state=window.state||{}; if(!state.sugoroku){state.sugoroku={count:30,exact:false,branchMode:'choice',pos:0,locked:false,currentMission:'START',dice:'🎲',missions:[],branches:{},routeChoices:{},history:[]}; autoSugoroku(false);} return state.sugoroku;}
function sugoAllMissions(type){ const custom=(sugorokuStateRaw().customMissions||[]); let base; if(type==='chaos') base=SUGO_MISSION_BANK.chaos.concat(SUGO_MISSION_BANK.talk,SUGO_MISSION_BANK.listener,SUGO_MISSION_BANK.penalty); else if(type==='listener') base=SUGO_MISSION_BANK.listener.concat(SUGO_MISSION_BANK.talk,SUGO_MISSION_BANK.chaos); else if(type==='penalty') base=SUGO_MISSION_BANK.penalty.concat(SUGO_MISSION_BANK.talk,SUGO_MISSION_BANK.chaos); else base=SUGO_MISSION_BANK.talk.concat(SUGO_MISSION_BANK.listener,SUGO_MISSION_BANK.chaos); return Array.from(new Set(base.concat(custom).filter(Boolean)));}
function sugoRegisterMission(v){const st=sugorokuStateRaw(); const text=String(v||'').trim(); if(!text)return; st.customMissions=Array.isArray(st.customMissions)?st.customMissions:[]; const all=Object.values(SUGO_MISSION_BANK).flat().concat(st.customMissions); if(!all.includes(text)){st.customMissions.push(text); st.history=st.history||[]; st.history.unshift(`${new Date().toLocaleTimeString()} ミッション登録：${text}`); st.history=st.history.slice(0,50);} }
function parseBranches(text){const out={}; (text||'').split(/\n+/).forEach(line=>{const m=line.match(/^\s*(\d+)\s*[:：]\s*(.+)$/); if(!m)return; const from=Number(m[1]); const arr=m[2].split(/[,、\s]+/).map(x=>Number(x)).filter(n=>Number.isFinite(n)&&n>from); if(arr.length)out[from]=arr;}); return out;}
function branchesToText(b){return Object.keys(b||{}).sort((a,c)=>a-c).map(k=>`${k}:${(b[k]||[]).join(',')}`).join('\n')}
function ensureMissions(st){st.missions=Array.isArray(st.missions)?st.missions:[]; const bank=sugoAllMissions('talk'); for(let i=0;i<st.count;i++){if(!st.missions[i])st.missions[i]=sugoPick(bank);} st.missions=st.missions.slice(0,st.count);}
function autoSugoroku(saveIt=true){const st=sugorokuStateRaw(); const type=document.getElementById('sugoAutoType')?.value||'talk'; st.count=Math.max(5,Math.min(120,Number(document.getElementById('sugoCount')?.value)||st.count||30)); st.exact=(document.getElementById('sugoExact')?.value||String(st.exact))==='true'; st.branchMode=document.getElementById('sugoBranchMode')?.value||st.branchMode||'choice'; const bank=sugoAllMissions(type); st.missions=Array.from({length:st.count},()=>sugoPick(bank)); st.branches={}; st.routeChoices={}; const branchN=Math.max(0,Math.floor(st.count/12)); for(let i=0;i<branchN;i++){const from=3+Math.floor(Math.random()*Math.max(1,st.count-8)); const a=Math.min(st.count,from+1+Math.floor(Math.random()*4)); const b=Math.min(st.count,from+3+Math.floor(Math.random()*7)); if(b>from+1)st.branches[from]=Array.from(new Set([a,b]));}
 st.pos=0; st.locked=false; st.currentMission='START'; st.dice='🎲'; st.history=st.history||[]; st.history.unshift(`${new Date().toLocaleTimeString()} ランダムマップ作成（${st.count}マス）`); st.history=st.history.slice(0,50); if(saveIt&&window.save)save(); renderSugoroku();}
function sugorokuStateRaw(){window.state=window.state||{}; state.sugoroku=state.sugoroku||{}; return state.sugoroku;}
function applySugorokuSettings(){const st=sugoState(); st.count=Math.max(5,Math.min(120,Number(document.getElementById('sugoCount')?.value)||30)); st.exact=(document.getElementById('sugoExact')?.value)==='true'; st.branchMode=document.getElementById('sugoBranchMode')?.value||'choice'; st.branches=parseBranches(document.getElementById('sugoBranches')?.value||''); const lines=(document.getElementById('sugoMissions')?.value||'').split(/\n+/).map(x=>x.trim()).filter(Boolean); if(lines.length){lines.forEach(sugoRegisterMission); st.missions=lines;} ensureMissions(st); if(st.pos>st.count)st.pos=0; if(window.save)save(); renderSugoroku();}
function sugoBranchLabel(st,from){const arr=(st.branches&&st.branches[from])||[]; if(!arr.length)return ''; const fixed=st.routeChoices&&st.routeChoices[from]; if(fixed)return `分岐${from}：${fixed===arr[0]?'A':'B'}ルート確定（${fixed}マス方面）`; return `分岐${from}：A/B未確定`;}
function routeText(st){const parts=[]; const choices=st.routeChoices||{}; for(let i=0;i<=st.count;i++){let label=i===0?'START':(i===st.count?'GOAL':String(i)); if(st.branches&&st.branches[i]){const arr=st.branches[i]||[]; const fixed=choices[i]; label+= fixed?` ⇢ ${fixed===arr[0]?'A':'B'}確定(${fixed})`:` ⇢ A:${arr[0]} / B:${arr[1]||arr[0]}`;} if(i===st.pos)label=`【${label}】`; parts.push(label); } return parts.join(' → ');}
function chooseBranchRoute(st,from){const arr=(st.branches&&st.branches[from])||[]; if(!arr.length)return from+1; st.routeChoices=st.routeChoices||{}; if(st.routeChoices[from])return st.routeChoices[from]; let picked=arr[0]; if(st.branchMode==='random'||st.branchMode==='roulette'){picked=sugoPick(arr); alert(`分岐マス ${from}：${picked===arr[0]?'A':'B'}ルートに決定！`);}else{const ans=prompt(`分岐マス ${from}\nAルート：${arr[0]}マス方面\nBルート：${arr[1]||arr[0]}マス方面\nA / B / 数字で選んでね`, 'A'); const v=String(ans||'A').trim().toUpperCase(); if(v==='B')picked=arr[1]||arr[0]; else if(v==='A')picked=arr[0]; else {const n=Number(v); picked=arr.includes(n)?n:arr[0];}}
 st.routeChoices[from]=picked; st.history=st.history||[]; st.history.unshift(`${new Date().toLocaleTimeString()} 分岐${from}：${picked===arr[0]?'A':'B'}ルート確定 → ${picked}マス方面`); return picked;}
function calcDest(st,step){let raw=st.pos+step; const arr=st.branches&&st.branches[st.pos]; if(arr&&arr.length){const routeStart=chooseBranchRoute(st,st.pos); raw=routeStart+step-1;} if(st.exact&&raw>st.count){const over=raw-st.count; return Math.max(0,st.count-over);} return Math.min(st.count,raw);}
function sugoCellHtml(st,i){return `${st.branches&&st.branches[i]?'<span class="sugo-cell-route">分岐</span>':''}<span class="sugo-cell-num">${i===0?'START':i===st.count?'GOAL':i+'マス'}</span><span class="sugo-cell-title">${i===0?'スタート':i===st.count?'ゴール':(st.missions[i-1]||'自由')}</span>`;}
function sugoMakeCell(st,i,extra=''){const div=document.createElement('button'); div.type='button'; div.className='sugo-cell '+extra+(i===st.pos?' current':'')+(i===st.count?' goal':'')+(st.branches&&st.branches[i]?' branch':'')+(st.locked&&i===st.pos?' locked':''); div.onclick=()=>editSugorokuCell(i); div.innerHTML=sugoCellHtml(st,i); return div;}
function renderSugorokuMap(st,map){map.innerHTML=''; const choices=st.routeChoices||{}; const branchKeys=Object.keys(st.branches||{}).map(Number).sort((a,b)=>a-b); const main=document.createElement('div'); main.className='sugo-route-block'; main.innerHTML='<div class="sugo-route-head"><span>Aルート（基本ルート）</span><span class="sugo-badge">常時表示</span></div><div class="sugo-route-grid"></div>'; const grid=main.querySelector('.sugo-route-grid'); for(let i=0;i<=st.count;i++)grid.appendChild(sugoMakeCell(st,i)); map.appendChild(main);
 branchKeys.forEach(from=>{const arr=st.branches[from]||[]; const fixed=choices[from]; const block=document.createElement('div'); block.className='sugo-route-block'; const bStart=arr[1]||arr[0]; const bEnd=Math.min(st.count, bStart+5); block.innerHTML=`<div class="sugo-route-head"><span>分岐 ${from} のルート選択</span><span class="sugo-badge">${fixed?('確定：'+(fixed===arr[0]?'A':'B')+'ルート'):'未確定'}</span></div><div class="sugo-branch-choice"><div class="sugo-choice-card ${fixed===arr[0]?'confirmed':''}"><div class="sugo-choice-label">Aルート</div><div>${arr[0]}マス方面へ進む基本ルート</div></div><div class="sugo-choice-card ${fixed===bStart?'confirmed':''}"><div class="sugo-choice-label">Bルート</div><div>${bStart}マス方面へ進む別ルート</div></div></div><div class="sugo-branch-note">Bルート表示：${bStart}〜${bEnd}マス付近</div><div class="sugo-route-grid" style="margin-top:8px"></div>`; const bg=block.querySelector('.sugo-route-grid'); for(let i=bStart;i<=bEnd;i++)bg.appendChild(sugoMakeCell(st,i,'b-route')); map.appendChild(block); });}
function rollSugoroku(){const st=sugoState(); if(st.locked){alert('ミッションをクリアするまで次のサイコロは振れないよ'); return;} if(st.pos>=st.count){alert('もうゴールしてるよ。位置リセットで最初から遊べる。'); return;} const d=1+Math.floor(Math.random()*6); st.dice=String(d); const dest=calcDest(st,d); st.pos=dest; st.currentMission=dest>=st.count?'🎉 ゴール！お疲れ様！':(st.missions[dest-1]||'自由トーク1分'); st.locked=dest<st.count; st.history.unshift(`${new Date().toLocaleTimeString()} ${d}マス進む → ${dest}${dest>=st.count?'（ゴール）':' / '+st.currentMission}`); st.history=st.history.slice(0,50); if(window.save)save(); renderSugoroku();}
function clearSugorokuMission(){const st=sugoState(); st.locked=false; st.history.unshift(`${new Date().toLocaleTimeString()} ミッションクリア：${st.currentMission}`); st.history=st.history.slice(0,50); if(window.save)save(); renderSugoroku();}
function resetSugorokuRun(){const st=sugoState(); st.pos=0; st.locked=false; st.currentMission='START'; st.dice='🎲'; st.routeChoices={}; st.history.unshift(`${new Date().toLocaleTimeString()} 位置リセット`); if(window.save)save(); renderSugoroku();}
function editSugorokuCell(i){if(i<=0)return; const st=sugoState(); const cur=st.missions[i-1]||''; const v=prompt(`${i}マス目のミッション\n未登録の内容を入れると、自動でミッション候補にも登録されます。`,cur); if(v!==null){const text=v.trim()||cur; st.missions[i-1]=text; sugoRegisterMission(text); if(window.save)save(); renderSugoroku();}}
window.renderSugoroku=function(){const st=sugoState(); ensureMissions(st); const $=id=>document.getElementById(id); if($('sugoCount'))$('sugoCount').value=st.count; if($('sugoExact'))$('sugoExact').value=String(!!st.exact); if($('sugoBranchMode'))$('sugoBranchMode').value=st.branchMode||'choice'; if($('sugoBranches'))$('sugoBranches').value=branchesToText(st.branches); if($('sugoMissions'))$('sugoMissions').value=st.missions.join('\n'); if($('sugoDice'))$('sugoDice').textContent=st.dice||'🎲'; if($('sugoMission'))$('sugoMission').textContent=st.currentMission||'START'; if($('sugoStatus'))$('sugoStatus').innerHTML=st.locked?'<span class="sugo-locked-note">ミッション未クリア：次のサイコロはロック中</span>':'<span class="sugo-cleared-note">サイコロOK</span>'; if($('sugoPositionBadge'))$('sugoPositionBadge').textContent=`現在：${st.pos}/${st.count}`; if($('sugoGoalBadge'))$('sugoGoalBadge').textContent=`ゴール：${st.count}マス`; if($('sugoRuleBadge'))$('sugoRuleBadge').textContent=st.exact?'ゴール：ピッタリのみ':'ゴール：通過OK'; if($('sugoRouteText'))$('sugoRouteText').textContent=routeText(st); if($('sugoHistory'))$('sugoHistory').textContent=(st.history&&st.history.length)?st.history.join('\n'):'履歴なし'; const map=$('sugoMap'); if(map){renderSugorokuMap(st,map);}  };
window.autoSugoroku=autoSugoroku;
document.addEventListener('DOMContentLoaded',function(){const b=(id,fn)=>{const el=document.getElementById(id); if(el)el.onclick=fn}; b('sugoRollBtn',rollSugoroku); b('sugoClearBtn',clearSugorokuMission); b('sugoResetRunBtn',resetSugorokuRun); b('sugoAutoBtn',()=>autoSugoroku(true)); b('sugoApplyBtn',applySugorokuSettings); ['sugoCount','sugoExact','sugoBranchMode'].forEach(id=>{const el=document.getElementById(id); if(el)el.onchange=applySugorokuSettings;}); try{renderSugoroku()}catch(e){console.warn(e)}});
})();
